name: Capstone Project Platform GCP Deployment
on:
  push:
    branches:
      - main

jobs:
    deploy:
        runs-on: ubuntu-latest


        steps:
            - name: First Step For Deployment
              run: echo "Starting GCP Deployment Process"

            - name: Checkout Repository
              uses: actions/checkout@v2

            - name: Second Step For Deployment
              run: echo "Finished GCP Deployment Process"



